name: persona
app_url: http://localhost:8000
app_port: 8000
build_steps:
  - pip install -r requirements.txt
  - cd frontend && npm install && npm run build

command: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
static_dir: frontend/dist

env:
  - name: "DATABRICKS_WAREHOUSE_ID"
    valueFrom: "sql-warehouse"
  - name: INPUT_TABLE
    value: "dev.default.bank_customer_data"
  - name: DATABRICKS_GENIE_SPACE_ID
    value: "01f01e27f6e4104fa7aa7359d5af5f68"
